### ISSUE TITLE
How to enter HTML markup?

### ISSUE THREAD

**Issue by mbrochh** [zsiciarz/django-markitup#2]
Sorry for the stupid question and it is probably better suited to be asked at the markitup repo but they don't have an issue tracker...

Is there a way to enter HTML markup into the editor? For example I would like to place a Google Maps iframe, but markitup always replaces all html tags with "MARKUP REMOVED".

**Comment by helloworldhahaha** [comment]
hello, I want to how to  choose local picture or audio,can you tell me

**Comment by Jiayi-Liao** [comment]
Same problem...
